### ISSUE TITLE
Awesome work! Looking forward to the code and dataset :)

### ISSUE THREAD

**Issue by Richar-Du** [vis-nlp/UniChart#1]

**Comment by AhmedMasryKU** [comment]
Hi @Richar-Du, 
Thanks for your interest in our work!
We are planning to release the training code and pretraining dataset in the next two weeks! 
In the meantime, feel free to use our simple inference code and model weights from huggingface for inference!

**Comment by Richar-Du** [comment]
Thanks, waiting for your wonderful work:)

**Comment by vbursztyn** [comment]
Hi @AhmedMasryKU,
Just following up on your plans for releasing the fine-tuning code.
We are considering including your model as a baseline in a paper submission due in ~4 weeks, so just wondering if timelines will possibly align.
Thank you for your work!

**Comment by AhmedMasryKU** [comment]
Apologies for the delay. I was busy with some deadlines. I have just added an example finetuning code to the repo. 
Please check and let me know if you have any questions!
Good luck with your submission!

**Comment by AhmedMasryKU** [comment]
The pretraining dataset has been released! Let me know if you have any questions!
