### ISSUE TITLE
Access to Pretraining Dataset Data Tables

### ISSUE THREAD

**Issue by rattandeep1998** [vis-nlp/UniChart#11]
I've been trying to locate the data tables associated with this dataset but have not been able to find them. 

Could you please provide guidance on where these data tables are available or point me to the appropriate repository or source where I can access them?

**Comment by AhmedMasryKU** [comment]
Hello, 

You can find the flattened data tables in the labels of this dataset: https://huggingface.co/datasets/ahmed-masry/unichart-pretrain-data

You need to filter the queries and only keep the rows that contains this prefix "<extract_data_table> "

Let me know if you have any questions.

**Comment by rattandeep1998** [comment]
Okay, thank you so much for the prompt response.
