### ISSUE TITLE
Could you provide a approximate time for the dataset's releasing?

### ISSUE THREAD

**Issue by 1292224662** [vis-nlp/UniChart#2]
It would be helpful for us, thanks in advance.

**Comment by AhmedMasryKU** [comment]
Hi @1292224662 
Thanks for your interest in our work!
We are planning to release the training code and pretraining dataset in the next two weeks!

**Comment by xiaofei05** [comment]
@AhmedMasryKU hi, is there any news?

**Comment by AhmedMasryKU** [comment]
Hi, we will release the dataset in the next few days! Stay tuned!

**Comment by AhmedMasryKU** [comment]
Apologies for the delay. I have just added the finetuning code. 
The dataset will be released in the next two days after finalizing the format. 

Thanks for your patience!

**Comment by AhmedMasryKU** [comment]
The pretraining dataset has been released! Let me know if you have any questions!
