### ISSUE TITLE
Can't access the Images from the drive link

### ISSUE THREAD

**Issue by ashim95** [vis-nlp/UniChart#3]
Hi,

Thank you for releasing the accompanying pre-training data for your paper. I am trying to access the images at the following link:
https://drive.google.com/file/d/1j5Kk51Kc5wsQyzuk2qM_WCQWYs-Kms42/view?usp=sharing 

But it says access denied, perhaps you need to enable link sharing?

Thanks,

**Comment by AhmedMasryKU** [comment]
Hi, 
It looks like my university changed their Google Drive Policy, so data sharing is no longer working. To provide access to the data, I uploaded the data to this huggingface dataset: https://huggingface.co/datasets/ahmed-masry/UniChart-pretrain-images 
I will also update the repo accordingly.

**Comment by AhmedMasryKU** [comment]
Closing this issue for now. Feel free to reopen if you have additional questions.
