### ISSUE TITLE
How to generate the template question and answer?

### ISSUE THREAD

**Issue by FanqingM** [vis-nlp/UniChart#4]
Hello
In paper, there says that We manually analyzed the exist- ing task datasets (e.g., ChartQA) to find the most common operations (e.g., sum, average, difference, etc.) and constructed 90 templates that we utilize to generate synthetic question and answer pairs. All the templates are provided in Appendix A.6.
I wonder how to generate this question and answer. Is there any code about is in your repo?

**Comment by AhmedMasryKU** [comment]
Hi @FanqingM, 

Unfortunately, we don't currently have any plans to release the code we used to generate the question/answer pairs for our pretraining dataset. We will let you know if we change our plans.
