### ISSUE TITLE
The format of fine-tune dataset

### ISSUE THREAD

**Issue by utilk9823** [vis-nlp/UniChart#9]
I want to fine-tune my dataset on my local computer, but I am encountering some problems while loading datasets. Is it possible for you to provide me with the format of the dataset you used for training? This would help me understand how to modify my local dataset to be suitable for loading it into the training environment.

**Comment by AhmedMasryKU** [comment]
Hey @utilk9823, 
You can format your data in a similar format to this https://huggingface.co/datasets/ahmed-masry/chartqa_without_images
